version: "3"

tasks:
  node-version:
    silent: true
    cmds:
      - echo "You are using Node.js version $(node --version);"
      - echo "however, the version $(cat .nvmrc) is required."
      - echo "Use NVM to install the correct version."
      - echo "See https://github.com/nvm-sh/nvm for details."
      - echo "Once NVM is installed, you should be able to run:"
      - echo "  nvm use"
      - echo "From the root directory of this repository to start"
      - echo "using the correct version."
      - exit 1
    status:
      - '[ "$(node --version)" == "$(cat .nvmrc)" ]'

  javascript-dependencies:
    silent: true
    deps: [node-version]
    sources:
      - package.json
      - pnpm-lock.yaml
    generates:
      - node_modules/.pnpm/lock.yaml
    cmds:
      - pnpm install

  dev:
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec next dev

  build:
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec next build

  storybook:
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec storybook dev

  dependency-graph:
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec depcruise src --include-only "^src" --output-type dot | dot -T svg > dependency-graph.svg
      - open dependency-graph.svg

  knip:
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec knip

  lint:
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec eslint --cache .

  format:
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec prettier . --write

  format-check:
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec prettier . --check
