version: "3"

tasks:
  node-version:
    silent: true
    run: once
    cmds:
      - echo "You are using Node.js version $(node --version);"
      - echo "however, the version $(cat .nvmrc) is required."
      - echo "Use NVM to install the correct version."
      - echo "See https://github.com/nvm-sh/nvm for details."
      - echo "Once NVM is installed, you should be able to run:"
      - echo "  nvm use"
      - echo "From the root directory of this repository to start"
      - echo "using the correct version."
      - exit 1
    status:
      - '[ "$(node --version)" == "$(cat .nvmrc)" ]'

  javascript-dependencies:
    silent: true
    run: once
    deps: [node-version]
    sources:
      - package.json
      - pnpm-lock.yaml
    generates:
      - node_modules/.pnpm/lock.yaml
    cmds:
      - pnpm install

  dev:
    run: once
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec next dev

  build:
    run: once
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec next build

  storybook:
    run: once
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec storybook dev

  dependency-graph:
    run: once
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec depcruise src --include-only "^src" --output-type dot | dot -T svg > dependency-graph.svg
      - open dependency-graph.svg

  knip:
    run: once
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec knip

  lint:
    run: once
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec eslint --cache .

  format:
    run: once
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec prettier . --write

  format-check:
    run: once
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec prettier . --check

  playwright-dependencies:
    run: once
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec playwright install --with-deps

  playwright:
    run: once
    deps: [playwright-dependencies]
    cmds:
      - pnpm exec playwright test

  vitest:
    run: once
    deps: [javascript-dependencies]
    cmds:
      - pnpm exec vitest run

  pre-commit:
    deps:
      - build
      - knip
      - lint
      - format-check
