name: Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run Eslint
        run: task lint
  format-check:
    name: format-check
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run Prettier
        run: task format-check
  knip:
    name: knip
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run Knip
        run: task knip
  vitest:
    name: vitest
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run Vitest Tests
        run: task vitest
  playwright:
    name: playwright
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run Playwright Tests
        run: task playwright
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  deploy:
    name: deploy
    environment: Production
    runs-on: ubuntu-latest
    needs:
      - eslint
      - format-check
      - knip
      - vitest
      - playwright
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
